version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - './nginx/conf:/etc/nginx/conf.d'
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      # 静的ファイルはnginxに配置してるものが使われる
      - ./mysite/static:/src/static
    depends_on:
      - django
    networks:
      app_net:
        ipv4_address: 172.30.0.4
  django:
    build: ./django
    container_name: django
    expose:
      - '8001'
    volumes:
      - './mysite:/src'
    command: uwsgi --socket :8001 --module mysite.wsgi
    depends_on:
      - mysql
    networks:
      app_net:
        ipv4_address: 172.30.0.3

    # command: 'python /src/manage.py runserver 0.0.0.0:8001'
  mysql:
    image: mysql:8.0
    container_name: docker_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db1'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    volumes:
      - './mysite/db/data:/var/lib/mysql'
      - './mysite/db/my.cnf:/etc/mysql/conf.d/my.cnf'
    networks:
      app_net:
        ipv4_address: 172.30.0.2

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24