"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "!ayx@2b^0u&rhf7jlqzj#*aj%8p19j(v)xg7@1#0j3c^s$*nh+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "sass_processor",
    "social_django",
    "app",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",  # social_django
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "mysite/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",  # social_django
                "social_django.context_processors.login_redirect",  # social_django
            ],
        },
    },
]
print(TEMPLATES)
WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    #  'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "db1",
        "USER": "testuser",
        "PASSWORD": "password",
        "HOST": "172.30.0.2",
        "OPTIONS": {"init_command": "SET sql_mode='STRICT_TRANS_TABLES'",},
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# open() "{nginx.confで設定したlocation /static}/{STATIC_URL}/main/css/site.css" failed (2: No such file or directory), client: 172.18.0.1, server: dockerhost, request:
# "GET /{STATIC_URL}/main/css/site.css HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/index/"
# テンプレートから呼び出すときのパス
STATIC_URL = "/static/"
# プロジェクト内で作成された各アプリケーション内にある静的フォルダを本番環境で集約する場所を設定できる
STATIC_ROOT = os.path.join(BASE_DIR, "static")
#######
LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/main"
LOGOUT_REDIRECT_URL = "/login"
#######
# Sass/SCSS
SASS_PROCESSOR_AUTO_INCLUDE = False
SASS_PROCESSOR_ROOT = os.path.join(BASE_DIR, "static")
SASS_PROCESSOR_INCLUDE_FILE_PATTERN = r"^.+\.(sass|scss)$"
SASS_PRECISION = 8
SASS_OUTPUT_STYLE = "compact"
SASS_TEMPLATE_EXTS = [".html", ".haml"]
#######
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
#######
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "babababeriru2010@gmail.com"
EMAIL_HOST_PASSWORD = "sorosann"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#######
# social_django
AUTHENTICATION_BACKENDS = (
    # 'social_core.backends.open_id.OpenIdAuth',
    # 'social_core.backends.google.GoogleOpenId',
    # 'social_core.backends.google.GoogleOAuth2',
    # 'social_core.backends.github.GithubOAuth2',
    "social_core.backends.twitter.TwitterOAuth",
    # 'social_core.backends.facebook.FacebookOAuth2',
    "django.contrib.auth.backends.ModelBackend",
)
SOCIAL_AUTH_TWITTER_KEY = ("PpI0YtMmgsN6vYnM4dH8eMN9C",)  # Consumer Key
SOCIAL_AUTH_TWITTER_SECRET = (
    "uLefXWvqni98rliTnrIMhg20pWBX81FhbmPKWNLLe6V96Z5Vrq"  # Consumer Secret
)
#######
AUTH_USER_MODEL = "app.User"

